CREATE TABLE [dbo].[INSCRITO]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Id_ALUMNO] INT NOT NULL, 
    [Cod_CURSO] INT NOT NULL, 
    CONSTRAINT [FK_INSCRITO_ALUMNO] FOREIGN KEY ([Id_ALUMNO]) REFERENCES [ALUMNO]([Id]), 
    CONSTRAINT [FK_INSCRITO_CURSO] FOREIGN KEY ([Cod_CURSO]) REFERENCES [CURSO]([COD])
)
